"""empty message

Revision ID: 120226accac8
Revises: 4e6a22cf2b4d
Create Date: 2023-12-06 19:08:08.529304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120226accac8'
down_revision = '4e6a22cf2b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_view', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('business_view')

    # ### end Alembic commands ###
