"""empty message

Revision ID: 3d9797e13a5e
Revises: 96487127738e
Create Date: 2023-12-01 12:40:43.673548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9797e13a5e'
down_revision = '96487127738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('businessView', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('businessId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'businesses', ['businessId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('businessId')
        batch_op.drop_column('businessView')

    # ### end Alembic commands ###
