"""empty message

Revision ID: 4e6a22cf2b4d
Revises: 3d9797e13a5e
Create Date: 2023-12-06 18:46:02.717263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6a22cf2b4d'
down_revision = '3d9797e13a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['owner_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_businessId_fkey', type_='foreignkey')
        batch_op.drop_column('isBusiness')
        batch_op.drop_column('businessView')
        batch_op.drop_column('businessId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('businessId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('businessView', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isBusiness', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_businessId_fkey', 'businesses', ['businessId'], ['id'])

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
