"""empty message

Revision ID: 96487127738e
Revises: ce827957eb4c
Create Date: 2023-11-30 23:46:59.201828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96487127738e'
down_revision = 'ce827957eb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isBusiness', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isBusiness')

    # ### end Alembic commands ###
