"""empty message

Revision ID: bfa972fcfaa1
Revises: 016b314f36a8
Create Date: 2023-11-30 15:43:36.281632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa972fcfaa1'
down_revision = '016b314f36a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
